### ISSUE TITLE
Duplicate Symbols w/ other plugins

### ISSUE THREAD

**Issue by theodusarcaedim** [Azure/azure-mobile-engagement-unity#5]
I'm trying to use this plugin in an existing project but I'm having an issue when I get to the Xcode build step. Xcode gives me linker errors regarding the following duplicate symbols: 
```
_kUnityDidFailToRegisterForRemoteNotificationsWithError
_kUnityDidReceiveLocalNotification
_kUnityDidReceiveRemoteNotification
_kUnityDidRegisterForRemoteNotificationsWithDeviceToken
_kUnityOnOpenURL
```

I took a peek at the source code and notice that these are being defined in EngagementUnity.m, but also in AppDelegateListener.m which is auto-generated by Unity. Do you have any suggestions for getting around this issue?

**Comment by ogoguel** [comment]
Weird: I agree  that there can be some duplicates, but I don't quite get why I didn't encounter into that case earlier...

Can you check this version https://github.com/ogoguel/azure-mobile-engagement-unity/tree/issue_5  to confirm if it resolved your issue (as I could not reproduce it on my end) ?

**Comment by theodusarcaedim** [comment]
Unfortunately I'm still encountering linker errors. I failed to mention before that I'm using Unity 5.4.1f1. I can build successfully if I include the plugin in an empty project, but the conflicts appear when I import it into an existing project with other 3rd party plugins. In my tests, I've narrowed the conflict down to the Google VR SDK plugin: a blank project with just the Azure Mobile Engagement plugin and GVR will produce the error.

Oddly enough, in 5.4.1f1 I only see errors for _kUnityDidReceiveLocalNotification and _kUnityOnOpenURL, but in 5.4.2f2 I see the five I mentioned in my original post.

**Comment by ogoguel** [comment]
Thanks for the info. I've been able to reproduce it using Unity 5.4.2f1 and installing the Google VR SDK. Here's a new tentative fix for your review :
https://github.com/ogoguel/azure-mobile-engagement-unity/tree/issue_5c

I am still puzzled about the various behaviors with previous versions of Unity though, but let's focus on the latest release!

**Comment by theodusarcaedim** [comment]
That seems to have fixed it! I no longer get linker errors. Thanks a ton! :)
