### ISSUE TITLE
Need bitcode support

### ISSUE THREAD

**Issue by goneale** [Azure/azure-mobile-engagement-unity#8]
Guys,

Receiving error when trying to archive:
```
ld: bitcode bundle could not be generated because '/Users/goneale/Documents/dev/projects/project/deploy/iOS/project_Dev_1.0.15/Libraries/EngagementPlugin/iOS/libEngagementUnity.a(EngagementUnity.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I am trying to build without bitcode now but this isn't desirable. Any ETA on a fix?

**Comment by goneale** [comment]
Couldn't build without bitcode due to Unity IAP then complaining. Between this and the Google Play error #9 I can't go live to either store. Sigh.

**Comment by ogoguel** [comment]
Arghhh! Building with the "enable bitcode" flag was not sufficient : for library, the `-fembed-bitcode` had to be added to the compiler settings. 

Fixed in https://github.com/Azure/azure-mobile-engagement-unity/pull/10

**Comment by goneale** [comment]
Awesome @ogoguel looking forward to this merge :)

**Comment by piyushjo** [comment]
Hi there, the native SDK itself doesn't support this at the moment so even if we do this at the wrapper layer, it wouldn't work. It is in our backlog with no ETA right now.
